# Generated by Django 3.0 on 2019-12-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('address', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('loan_amount', models.IntegerField(default=0)),
                ('is_allocated', models.BooleanField(default=False)),
                ('loan_sanction_date', models.DateField(null=True)),
                ('loan_paid', models.IntegerField(default=0)),
                ('due_amount', models.IntegerField(default=0)),
                ('due_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'loan_details',
            },
        ),
    ]
