# Generated by Django 3.0 on 2019-12-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetails',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
