# Generated by Django 3.0 on 2019-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20191218_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='no_of_time',
            field=models.IntegerField(default=0),
        ),
    ]
