# Generated by Django 3.0 on 2019-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_remove_loandetails_no_of_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='unique',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
