# Generated by Django 3.0 on 2019-12-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_loandetails_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='profile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
