# Generated by Django 3.0 on 2019-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_loandetails_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetails',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
